### ISSUE TITLE
Character stats being duplicated

### ISSUE THREAD

**Issue by MidnightLightning** [EneaAntonicelli/unit-4-game#3]
https://github.com/EneaAntonicelli/unit-4-game/blob/b9203c27fd462168f0c8a718cbe526757f1dc0ed/assets/javascript/Non-Dynamic.js#L69-L74

When selecting a hero, the stats beneath each hero (the one you selected and all the others) get filled in repeated times. That's due to the jQuery selector `$('.character .stats')` on line 69 not being specific enough.

That query tells jQuery to go find all items that have a class of `character`, and find anything inside them with a class of `stats`. In the HTML, each character has three `h3` tags that have a class of `stats`, which is why the duplication is happening.

And you don't want it on _all_ the characters (probably?), just the one hero you picked. So, instead of `$('.character .stats')`, you want `$(this)` to get a jQuery object referring to just the one character that was picked. Then using the jQuery `find` function, you can search for things just inside that object:

```js
$character = $(this);
$character.find('.technique').append(heroData.technique);
$character.find('.health').append(heroData.hp);
```

**Comment by EneaAntonicelli** [comment]
I might need to pull the append data out of that function since those stats should display on the character selections prior to me even picking a character. Then they should carry over with the selected character. Basically it should allow the user to view the stats prior to choosing the character, no?

**Comment by EneaAntonicelli** [comment]
Furthermore, using (this) is bypassing the text and format already in the html:

![image](https://user-images.githubusercontent.com/16923041/42128571-719941bc-7c63-11e8-9bbd-678f60b4ec3e.png)

**Comment by MidnightLightning** [comment]
Yes, that would be a good thing; probably create an action on document ready, before defining your click-handler that loops through all the characters' and puts their data in to the HTML. The jQuery [each](https://api.jquery.com/each/) function would help you there; something like:

```js
$('.character').each(function(index) {
  var $character = $(this);
  var characterData = characterDict[this.id];
  $character.find('.technique').append(characterData.technique);
  // etc.
});
```

**Comment by EneaAntonicelli** [comment]
Ok I got that part to work. New issues: 

A. Attack button is giving me a NAN output. 
B. The way the stats are displayed under the chosen characters is squished. This is because it is taking the original 2 column width, and then putting that into the new 4 column width of it's destination.. I cant seem to overwrite this so that the stats are not squished... 

That is less of an issue for the time being than getting the overall logic to calculate and display.
